services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: management_app
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
   

volumes:
  postgres_data:
    driver: local